language: swift
osx_image: xcode8.3
#branches:
#  only:
#    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT="DSPopup.xcodeproj"
  - SCHEME="DSPopup"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;